### PR TITLE
Improve SSH config file parsing logic

### PR DESCRIPTION
**Pull request by pmatseykanets**
Sections separated by Host and (or) Match keywords, not empty lines.
Arguments can be optionaly double quoted.
Sections can contain both comments and empty lines.
Declarations in Match sections are not collected.

Tests are included.

Source: ```$ man ssh_config.``` 

Essential parts:
The configuration file has the following format:
     Empty lines and lines starting with `#' are comments.  Otherwise a line is of
     the format ``keyword arguments''.  Configuration options may be separated by
     whitespace or optional whitespace and exactly one `='; the latter format is
     useful to avoid the need to quote whitespace when specifying configuration
     options using the ssh, scp, and sftp -o option.  Arguments may optionally be
     enclosed in double quotes (") in order to represent arguments containing spa-
     ces. 

... note that keywords  are case-insensitive and arguments are case-sensitive ...

Host    Restricts the following declarations (up to the next Host or Match
             keyword) to be only for those hosts that match one of the patterns
             given after the keyword.
Match   Restricts the following declarations (up to the next Host or Match
             keyword) to be used only when the conditions following the Match key-
             word are satisfied.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Envoy has been out for a while now without this being an issue, so am just going to hold off on complicating it further.

**Comment by pmatseykanets** [comment]
@taylorotwell This is really unfortunate because Envoy currently breaks on a perfectly valid ssh config files. This is super important when you have dozens of configurations that have been accumulated and shared between teams.

Is there anything that I can do to improve/"simplify" (or do differently) this PR to make it considered for merging?

I did this PR out of necessity. We at our agency would love to use envoy but can't reformat all ssh configs  to make it happen, and more importantly to keep remembering at all times that it doesn't support valid format.

In any case thanks for your time and consideration.

**Comment by taylorotwell** [comment]
Done and tagged.

**Comment by pmatseykanets** [comment]
@taylorotwell Thank you so much! :+1:

**Pull request merged**
