### PR TITLE
Add symfony 3.0 support

### PR DESCRIPTION
**Pull request by Butochnikov**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This breaks earlier 2.x support. Please update the version constraints to remove the various 2.x versions no longer supported. I think 2.6 upwards, or something. Please check this.

**Comment by Butochnikov** [comment]
Not breaks.
Envoy by default install Symfony\Console 2.8.4
I tested my code on the 2.8 and 3.0, everything works fine .

History of question see here: https://github.com/laravel/framework/issues/13402

a1d9bee4f34bd753481d8ef1cae908e8

**Comment by GrahamCampbell** [comment]
> Envoy by default install Symfony\Console 2.8.4

Not the point, You MUST change the version constraint to reflect the actual minimum 2.x requirement.

**Comment by taylorotwell** [comment]
Yeah we would have to change version constraint to ~2.8 instead of ~2.3.

**Comment by sebestenyb** [comment]
Any news on this?

Confirming tasks is not possible with the latest envoy along with a brand new, blank laravel project and a simple Envoy.blade.php like below fails with this error.

```
@servers(['test' => 'localhost'])

@task('test', ['on' => 'test', 'confirm' => true])
        ls -la
@endtask
```

**Comment by dani3l** [comment]
had to downgrade to ~1.1.0 to resolve this

**Comment by fosron** [comment]
Still not working

**Pull request closed without merging**
